# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: shohei itoh
website: http://www.4696.co.jp/
email: itoh@4696.co.jp
description: > # this means to ignore newlines until "baseurl:"
  伊藤庄平。株式会社シロクロのデザイナー。フロントエンドを勉強するためのブログです。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://itoh.github.io" # the base hostname & protocol for your site
twitter_username: 9d
github_username:  itoh

# Build settings
markdown: kramdown
